[package]
name = "auxtrate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frame-support = "21.0.0"
log = "0.4.17"
sp-weights = "19.0.0"
